### ISSUE TITLE
Program crashing

### ISSUE THREAD

**Issue by hdfsyu** [popdynamite5511/2craft#1]
Traceback (most recent call last):
  File "E:\2craft-b.1.0_1\main.py", line 292, in <module>
    screen.register_shape(playerImg)
  File "C:\Users\viyaa\AppData\Local\Programs\Python\Python39\lib\turtle.py", line 1136, in register_shape
    raise TurtleGraphicsError("Bad arguments for register_shape.\n"
turtle.TurtleGraphicsError: Bad arguments for register_shape.
Use  help(register_shape)
There is an invalid syntax error in the code I believe...

**Comment by popdynamite5511** [comment]
This is now fixed, I am making a new release as I speak.
